### ISSUE TITLE
When running the CD install, I get error with the DB install

### ISSUE THREAD

**Issue by rahm0277** [Kieranties/SIfSug#2]
I'm having an issue running the CD install. I get an error similar to this: https://community.sitecore.net/developers/f/5/t/8269

I guess the question is that when the CD installation is running, is there a way to skip the DB deploy? Bigger question is - is the DB deploy needed? Does the CD installation do anything with the DBs?

**Comment by Kieranties** [comment]
Many apologies for the delay in responding here!

You would need to adjust the parameters passed to the WDP in the configs to prevent the WDP from performing an action.
You can see an example in the example repo from @Eldbom here: https://github.com/Eldblom/sifdemos/blob/4177ad65cdea2307b7a3d7ef1dadc101da3fcf6e/3_cd/Configs/sitecore-XM1-cd2.json#L196
This will prevent any sqlscript or dacfx package being deployed.

A more complex skip selection is here: https://github.com/Eldblom/sifdemos/blob/4177ad65cdea2307b7a3d7ef1dadc101da3fcf6e/2_xm0/Configs/sitecore-xm0.json#L202
This will skip objects of a specific type and name.  If you crack open the WDP and take a look at the archive.xml you'll see how the entries are identified
